server:
  port: 40015
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#     client-auth: need
#    trust-store: classpath:truststore.p12
#    trust-store-password: changeit
spring:
  application:
    name: active-life
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
    health:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s,recordStats
  datasource:
    url: jdbc:postgresql://active-life:5432/active_life
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Logs security-related events (use TRACE for even more details)
    org.springframework.web: DEBUG       # Logs incoming requests
    org.springframework.data.jpa: DEBUG  # Logs JPA queries
    org.hibernate.SQL: DEBUG             # Logs raw SQL statements
    org.hibernate.type.descriptor.sql: TRACE  # Logs SQL query parameters (optional)
