
server:
  port: 40015
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
   # client-auth: need
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
  http2:
    enabled: true
spring:
  application:
    name: active-life
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
    health:
  security:
    user:
      name: user
      password: password123
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s,recordStats
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
