server:
  port: 40015
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:activelife.p12
#    key-store-password: changeit
#    client-auth: need
#    trust-store: classpath:activeLifeCanadaTruststore.p12
#    trust-store-password: changeit
#    trust-store-type: PKCS12
spring:
  application:
    name: active-life
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s,recordStats
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-69216149.okta.com/oauth2/ausnnvikrcQbK6mZ05d7/v1/keys

jwt:
  secret: your-256-bit-secret  # Replace with a Base64-encoded secret key

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Logs security-related events (use TRACE for even more details)
    org.springframework.web: DEBUG       # Logs incoming requests
    org.springframework.data.jpa: DEBUG  # Logs JPA queries
    org.hibernate.SQL: DEBUG             # Logs raw SQL statements
    org.hibernate.type.descriptor.sql: TRACE  # Logs SQL query parameters (optional)
