server.port: 8082

spring:
  application.name: ems
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queue:
      ensqueue: queue
  jms:
    pub-sub-domain: false
  twilio:
    account:
      sid: ${TWILIO_ACCOUNT_SID}
    auth:
      token: ${TWILIO_AUTH_TOKEN}
