name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: appleboy/ssh-action@v1
      env:
        IMAGE: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd $DEPLOY_PATH
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull $IMAGE
          IMAGE=$IMAGE docker compose up -d --remove-orphans
