version: "3.8"

services:
  app:
    image: ghcr.io/manpreetkaurfullstacklabs/maka-boca-active-life-ca:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/active_life
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - boca-network
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: active_life
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - boca-network

volumes:
  db-data:

networks:
  boca-network:
    driver: bridge
