services:
  app:
    image: leofoto/boca-spring-boot-app-instance  # Name of the Spring Boot Docker image
    build: .
    #platform: linux/arm64
    ports:
      - "8080:8080"
    environment:
<<<<<<< HEAD
      SPRING_DATASOURCE_URL: jdbc:postgresql://active-life:5432/active_life
=======
      SPRING_DATASOURCE_URL: jdbc:postgresql://dgit b:5432/active_life
>>>>>>> faa7f71 (final commit)
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - boca-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: active_life
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - boca-network

volumes:
  db-data:

networks:
  boca-network:
    driver: bridge
