name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: maka-boca-active-life-ca

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set lowercase repo owner
      id: lower
      run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ../../active-life
        file: ../../active-life/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.lower.outputs.owner }}/maka-boca-active-life-ca:sha-${{ github.sha }}
